// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // O CLI (migrate, db push, studio) usa a conexão direta — migrations
    // não funcionam bem via pooler em modo transaction. O app em runtime
    // (src/lib/db.ts) lê DATABASE_URL direto do env, sem passar por aqui.
    url: process.env["DIRECT_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
